#!/bin/bash

if [ "$1" == "" ] ; then
	echo "Examples:"
	echo "  Scan disk1 "
	echo "    sudo md5recurse --globaldir /mnt/user/md5 -p disk1 /mnt/disk1"
	echo "  After disk failure: Find missing files (disable local and file attributes, enable global)"
	echo "    sudo md5recurse --globaldir /mnt/user/md5 --disable-file-attributes --onlyPrintMissing -p disk1 /mnt/disk1"
	echo "  After disk failure: Check MD5  (disable local and file attributes, enable global)"
	echo "    sudo md5recurse --globaldir /mnt/user/md5 --disable-file-attributes --check -p disk1 /mnt/disk1"
	echo "  Check md5's of current dir "
	echo "    md5recurse --enableLocalMd5Data --enableLocalMd5Sum --check -p user ."
	echo "  Print md5's to stdout similar to md5sum"
	echo "    md5recurse --print ."	
	echo
	exit 1
fi

/boot/app/md5recurse/bin/md5recurse -e UTF-8-BOM "$@"

