#!/bin/bash

echo "Cleaning incorrectly placed md5data"
# Note Dirs with  a '.disable_md5' will be skipped
for SCAN_DIR in /mnt/disk* /mnt/cache; do
	for SCAN_DIR2 in /mnt/disk* /mnt/cache; do
		if [ "$SCAN_DIR" != "$SCAN_DIR2" ] ; then
			# For debugging: Remove & to make it easier to break and kill for-loop process
			WRONGDISK=$(basename $SCAN_DIR2)
			echo "Cleaning .${WRONGDISK}.md5 and .${WRONGDISK}.md5data from ${SCAN_DIR}"
			find  ${SCAN_DIR} -name ".${WRONGDISK}.md5" -delete
			find  ${SCAN_DIR} -name ".${WRONGDISK}.md5data" -delete
		fi
	done
done
