#!/bin/bash
#SCALA=/mnt/cache/app/scala/bin/scala
JAVA_HOME=/mnt/cache/app/java/jre
#CLASSPATH=/mnt/cache/app/source/classes

if [ "$1" == "" ] ; then
	scala -J-Xmx1024M /boot/bin/scala/Md5Recurse.jar
	echo "Examples:"
	echo "  sudo md5recurse --globaldir /mnt/user/md5 -p disk1 /mnt/disk1"
	echo "  md5recurse --enableLocalMd5Data --enableLocalMd5Sum -p user ."
	echo "  md5recurse --print ."	
	echo
	exit 1
fi

#echo "Running: scala -J-Xmx1024M $DEBUG /boot/bin/scala/Md5Recurse.jar -e UTF-8-BOM $@"
scala -J-Xmx1024M $DEBUG /boot/bin/scala/Md5Recurse.jar -e UTF-8-BOM "$@"

