#!/bin/bash
#SCALA=/mnt/cache/app/scala/bin/scala
#JAVA_HOME=/mnt/cache/app/java/jre

if [ "$1" == "" ] ; then
	echo "Syntax: sudo md5recurse_dir ."
	echo
	exit 1
fi

execMd5recurse() {
	java -Xmx1024M $DEBUG -jar /boot/bin/Md5Recurse.jar "$@"
}

#scala -J-Xmx1024M $DEBUG /boot/bin/scala/Md5Recurse.jar -e UTF-8-BOM -p user --enableLocalMd5Data --enableLocalMd5Sum "$@"
execMd5recurse -e UTF-8-BOM -p user --enableLocalMd5Data --enableLocalMd5Sum "$@"
